name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Stop wasting time caching packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending usage data to Microsoft

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # dont fail all builds after first failure
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: .NET Restore
        run: dotnet restore
      
      - name: .NET Build
        run: dotnet build -c Release --no-restore --verbosity diag #detailed
